spring:
  application:
    name: hubService
  datasource:
    url: jdbc:postgresql://localhost:5432/guaranteeRateDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update